FROM ghcr.io/insight-platform/savant-deepstream-l4t:0.5.13-7.0

RUN --mount=type=cache,target=/var/lib/apt/lists \
    apt-get update && apt-get install -y \
    build-essential \
    pkg-config \
    curl \
    git \
    unzip

RUN --mount=type=bind,source=.,target=/opt/scripts bash /opt/scripts/docker/install-basic-deps.sh

WORKDIR /opt