FROM quay.io/pypa/manylinux_2_28_aarch64 AS base


RUN --mount=type=bind,source=.,target=/opt/scripts bash /opt/scripts/docker/install-basic-deps-manylinux.sh
ENV PATH="/root/.cargo/bin:/opt/python/cp310-cp310/bin:/opt/python/cp312-cp312/bin:$PATH"
RUN --mount=type=bind,source=.,target=/opt/scripts bash /opt/scripts/docker/install-basic-deps.sh

WORKDIR /opt

FROM base AS chef
ENV PATH="/root/.cargo/bin:$PATH"
RUN rustc -V

