FROM python:3.13

# Install dependencies needed for Rust
RUN --mount=type=cache,target=/var/lib/apt/lists \
    apt-get update && apt-get install -y \
    build-essential \
    pkg-config \
    curl \
    git

WORKDIR /opt

RUN --mount=type=bind,source=docker/install-basic-deps.sh,target=/opt/install-basic-deps.sh bash /opt/install-basic-deps.sh
